apiVersion: apps/v1
kind: Deployment
metadata:
 name: sonarqube
spec:
  selector:
    matchLabels:
     app: sonarqube
  replicas: 1
  template:
    metadata:
      name: sonarqube
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
          - name: sonarport
            containerPort: 9000
        env:
        - name: "SONARQUBE_JDBC_USERNAME"
          value: "postgres"
        - name: "SONARQUBE_JDBC_URL"
          value: "jdbc:postgresql://postgres:5432/postgres"
        - name: "SONARQUBE_JDBC_PASSWORD"
          value: "root"
        volumeMounts:
        - mountPath: /opt/sonarqube/data/
          name: sonar-data
        - mountPath: /opt/sonarqube/extensions/
          name: sonar-extensions        
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
            claimName: sonar-data
      - name: sonar-extensions
        persistentVolumeClaim:
            claimName: sonar-extensions
---
apiVersion: v1
kind: Service
metadata:
    name: sonarqube
spec:
  ports:
    - name: sonarport
      port: 9000
  selector:
    app: sonarqube
  type: LoadBalancer